# Generated by Django 6.0 on 2025-12-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_campaign_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('MEDICAL', 'Medical & Health'), ('EDUCATION', 'Education'), ('DISASTER', 'Disaster Relief'), ('HUMANITY', 'Humanity'), ('ANIMAL', 'Animal Welfare'), ('RELIGIOUS', 'Religious'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
