# Generated by Django 6.0 on 2025-12-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_campaign_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('MEDICAL', 'Medical & Health'), ('EDUCATION', 'Education'), ('DISASTER', 'Disaster Relief'), ('HUMANITY', 'Humanity'), ('ANIMAL', 'Animal Welfare'), ('RELIGIOUS', 'Religious')], default='MEDICAL', max_length=20),
        ),
    ]
